name: Deploy Terraform

on:
  push:
    branches: 
      - features/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (e.g., dev, qa, uat, prod)'
        required: true
        default: ''
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod


jobs:
  terraform:
    name: 'Terraform Apply on Azure'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set ARM environment variables
        run: |
          echo "ARM_CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)" >> $GITHUB_ENV
        
        
      - name: Terraform Init with Dynamic Backend
        run: |
          terraform init \
            -backend-config="key=${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="resource_group_name=rg-tfstate" \
            -backend-config="storage_account_name=tfstatestorageacct" \
            -backend-config="container_name=tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
